aux2/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mascotas/', include('mascotas.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mascotas/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name=''),
    path('<int:humano>', views.humano, name='humano'),
    path('subir_foto/<int:animal>', views.subir_foto, name='subir_foto'),
    path('animal/<int:mascota>', views.detalles_animal, name='detalles_animal'),
]

mascotas/models.py
from django.contrib.auth.models import User
from django.db import models


class Fruta(models.Model):
    nombre = models.CharField(max_length=30)
    puntos_salud = models.IntegerField(default=0)

    def __str__(self):
        return self.nombre


class Especie(models.Model):
    nombre = models.CharField(max_length=30)
    fruta_favorita = models.ForeignKey(Fruta, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.nombre


class Humano(models.Model):
    # En general usaríamos models.CASCADE, pero lo dejaremos así para no botar lo que tenemos hasta ahora
    usuario = models.OneToOneField(User, models.SET_NULL, null=True)
    nombre = models.CharField(max_length=30)

    def __str__(self):
        return self.nombre


class Animal(models.Model):
    especie = models.ForeignKey(Especie, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=30)
    salud = models.IntegerField('Puntos de salud', default=0)
    humano = models.ForeignKey(Humano, on_delete=models.SET_NULL, blank=True, null=True)
    imagen = models.ImageField(upload_to='fotitos', default='fotitos/sin_fotito.jpg')

    def __str__(self):
        return '%s (%s)' % (self.nombre, self.especie.nombre)

    class Meta:
        verbose_name_plural = "Animales"

mascotas/forms.py
from django import forms


class AgregarFotoMascota(forms.Form):
    imagen = forms.ImageField()

mascotas/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from mascotas.forms import AgregarFotoMascota
from mascotas.models import Animal


def index(request):
    animales = Animal.objects.all()
    return render(request, 'mascotas/index.html', {'animales': animales})


def humano(request, humano):
    animales = Animal.objects.filter(humano_id=humano)
    return render(request, 'mascotas/index.html', {'animales': animales})


def subir_foto(request, animal):
    animal = Animal.objects.get(id=animal)
    if request.method == 'POST':
        if request.user.id != animal.humano.usuario_id:
            return HttpResponse('t piyé', status=401)
        form = AgregarFotoMascota(request.POST, request.FILES)
        if form.is_valid():
            animal.imagen = form.cleaned_data['imagen']
            animal.save()
    return redirect('detalles_animal', mascota=animal.id)


def detalles_animal(request, mascota):
    animal = Animal.objects.get(id=mascota)
    return render(request, 'mascotas/detalles_mascota.html', {'mascota': animal})

templates/mascotas/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

    <title>Página de mascotas</title>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

templates/mascotas/detalles_mascota.html
{% extends 'mascotas/base.html' %}

{% block content %}
    <div class="container mt-3">
        <h1 class="text-center">Detalles de mascota</h1>
        <hr/>
    </div>
    <div class="container">
        <p><b>Nombre: </b> {{ mascota.nombre }}</p>
        <p><b>Especie: </b> {{ mascota.especie }}</p>
        <p><b>Humano: </b> <a href="{% url 'humano' humano=mascota.humano_id %}">{{ mascota.humano }}</a></p>
        <p><b>Foto: </b></p>
        <img src="{{ mascota.imagen.url }}" class="img-fluid">
        {% if mascota.humano.usuario_id == user.id %}
        <p>Si lo deseas, puedes cambiar la foto: </p>
        <form action="{% url 'subir_foto' animal=mascota.id %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <p><input id="id_imagen" type="file" name="imagen"></p>
            <input type="submit" value="Subir"/>
        </form>
        {% endif %}
    </div>

{% endblock %}

templates/mascotas/index.html
{% extends 'mascotas/base.html' %}

{% block content %}
    <div class="container mt-3">
        <h1 class="text-center">Directorio de mascotas</h1>
        <hr/>
    </div>


    <div class="container row offset-md-1">
    {% for animal in animales %}
        <div class="col-md-4 mb-3">
            <div class="card">
                <div class="card-body">
                    <img class="card-img-top mb-2" src="{{ animal.imagen.url }}" alt="Card image cap">
                    <h5 class="card-title">{{ animal.nombre }}</h5>
                    <p class="card-subtitle text-muted mb-2">{{ animal.especie }}</p>
                    <div class="card-text">Comida favorita: {{ animal.especie.fruta_favorita }}</div>
                    <div class="card-text">Puntos de vida: {{ animal.salud }}</div>
                    <a href="{% url 'humano' humano=animal.humano_id %}" class="card-link">Ver Dueño</a>
                    <a href="{% url 'detalles_animal' mascota=animal.id %}" class="card-link">Ver Detalles</a>
                </div>
            </div>
        </div>
    {% endfor %}
    </div>
{% endblock %}